# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_id', models.IntegerField(default=0, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=200, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizefilter.Product')),
            ],
        ),
    ]
