# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sizefilter', '0002_auto_20160404_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_variants',
            old_name='product_id',
            new_name='product',
        ),
    ]
