# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizefilter', '0003_auto_20160404_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variants',
            name='sku_code',
            field=models.CharField(max_length=200),
        ),
    ]
